try:
    print(a)
except NameError as erro:
    print('Erro: ', erro)